### ISSUE TITLE
Struct level `#[builder(Default=!)]` is making optional fields instead of required

### ISSUE THREAD

**Issue by RustyNova016** [loganmzz/macon-rs#32]
`#[builder(Default=!)]` on a struct still make its fields optional. I don't even implement Default on Foo.

```rust
#[derive(Builder)]
#[builder(Default=!)] // I want to force setting `uni`
pub struct Foo {
    uni: i8,
}

impl Foo {
    fn build_me() {
        let foo_build: FooBuilder = Foo::builder();
        let bar = foo_build.build(); // Still compile ?!
    }
}
```

However field level works:

```rust
#[derive(Builder)]
pub struct Foo {
    #[builder(Default=!)] // I want to force setting `uni`
    uni: i8,
}

impl Foo {
    fn build_me() {
        let foo_build: FooBuilder = Foo::builder();
        let bar = foo_build.build(); // No compiling!
    }
}
```

**Comment by loganmzz** [comment]
Hi @RustyNova016 ,

`#[builder(Default=!)]` on a struct is only applied to struct itself.

Applying to whole struct (aka fields) isn't currently supported. I will add nested `fields` attribute for claritification with associated `Default` support (including enforcement support).

Thank you for the feedback!

**Comment by RustyNova016** [comment]
Oh I see. Would be nice to have the option to apply to the whole struct, but I guess I'll have to wait for it.

**Comment by loganmzz** [comment]
> Oh I see. Would be nice to have the option to apply to the whole struct, but I guess I'll have to wait for it.

I may implement it this week-end, but test completeness for releasing may took few additional days. Expect it into a 1 week :)

**Comment by loganmzz** [comment]
@RustyNova016 `1.2.0` has been released: https://github.com/loganmzz/macon-rs/releases/tag/1.2.0

**Comment by RustyNova016** [comment]
Thanks! Gonna update now
